[info]
name = "TIMER0"
desc = "8-Bit Timer/Counter0 with PWM"

[[int]]
name = "TIMER0_COMPA"
desc = "Timer/Counter0 Compare Match A"
vect = 21

[[int]]
name = "TIMER0_COMPB"
desc = "Timer/Counter0 Compare Match B"
vect = 22

[[int]]
name = "TIMER0_OVF"
desc = "Timer/Counter0 Overflow"
vect = 23

#---------------------------------------------------------------------#
[[reg]]
name = "TIFR"
desc = "Timer Interrupt Flag Register"
addr = "0x35"
fields = [
    {name="OCF_B", desc="Output Compare B Match Flag", rnge="2:2"},
    {name="OCF_A", desc="Output Compare A Match Flag", rnge="1:1"},
    {name="TOV",   desc = "Timer Overflow Flag",       rnge="0:0"},
]

#---------------------------------------------------------------------#
[[reg]]
name = "TCCR_A"
desc = "Timer/Counter Control Register A"
addr = "0x44"
fields = [
    {name="COM_A", desc="Compare Match Output A Mode",       rnge="7:6"},
    {name="COM_B", desc="Compare Match Output B Mode",       rnge="5:4"},
    {name="WGM0",  desc="Waveform Generation Mode Bits 1:0", rnge="1:0"},
]

#---------------------------------------------------------------------#
[[reg]]
name = "TCCR_B"
desc = "Timer/Counter Control Register B"
addr = "0x45"

[[reg.fields]]
name = "FOC_A"
desc = "Force Output Compare A"
rnge = "7:7"
cstm = """\
<access>write-only</access>
"""

[[reg.fields]]
name = "FOC_B"
desc = "Force Output Compare B"
rnge = "6:6"
cstm = """\
<access>write-only</access>
"""

[[reg.fields]]
name = "WGM2"
desc = "Waveform Generation Mode Bit 2"
rnge = "3:3"

[[reg.fields]]
name = "CS"
desc = "Clock Select"
rnge = "2:0"

#---------------------------------------------------------------------#
[[reg]]
name = "TCNT"
desc = "Timer/Counter Register"
addr = "0x46"

#---------------------------------------------------------------------#
[[reg]]
name = "OCR_A"
desc = "Timer Output Compare Register A"
addr = "0x47"

#---------------------------------------------------------------------#
[[reg]]
name = "OCR_B"
desc = "Timer Output Compare Register B"
addr = "0x48"

#---------------------------------------------------------------------#
[[reg]]
name = "TIMSK"
desc = "Timer Interrupt Mask Register"
addr = "0x6E"
fields = [
    {name="OCIE_B", desc="Output Compare Match B Interrupt Enable", rnge="2:2"},
    {name="OCIE_A", desc="Output Compare Match A Interrupt Enable", rnge="1:1"},
    {name="TOIE",   desc="Timer Overflow Interrupt Enable",         rnge="0:0"},
]
